### ISSUE TITLE
Free monad

### ISSUE THREAD

**Issue by ev45ive** [fantasyland/fantasy-land#104]
Is there a fantasy-land compatible specification or better - implementation of Free monad?
I am mostly interested in building AST/DSL and Interpreters with interpreters combinators possibly.

**Comment by SimonRichardson** [comment]
The only one I've personally seen is the [monet.js](https://github.com/cwmyers/monet.js/blob/master/src/main/javascript/monet.js#L769) version. Although it would be good to have a fantasy land version as well.

**Comment by ev45ive** [comment]
I've seen monet.js. What i am afraid its not "connected to ecosystem". It has many aliases for methods, maybe it would be good idea to try run it against fantasy spec land tests suite?

Have you seen any example of interpreter build using Monet.js @SimonRichardson? I tried it following scala examples and have some difficulties doing it without matchers and case classes. #still_learning ;-)

**Comment by SimonRichardson** [comment]
Seems like @joneshf is doing somethings around Free and Coyenda (what you need to convert a constructor to a functor). I'm not 100% up to date with using Free to create a DSL, but I'm very interested in learning. 

https://github.com/joneshf/abstractions/tree/master/src

Purescript seems to have a lot of nice code around this idea of Free, so there are a lot of ideas that can be looked at there as well.

**Comment by SimonRichardson** [comment]
Ha, in fact it's got this tutorial of [Free](http://underscore.io/blog/posts/2015/04/14/free-monads-are-simple.html) [here](https://github.com/joneshf/abstractions/blob/master/src/orchestration.js#L198)

**Comment by joneshf** [comment]
Yep, I've been playing with them a bit lately. I was going to make a library once I felt more confident with them. I can push it up sooner rather than later though. Like @ev45ive, I've found monet just a bit cumbersome to use without support for natural transformations, matching, or some kind of catamorphism.

**Comment by SimonRichardson** [comment]
@joneshf that would be awesome... I've been looking at your examples and trying to [understand them myself](https://github.com/SimonRichardson/fantasia). I'm trying to understand the "orchestration" version, in general how it recurses through the interpreter.

**Comment by ev45ive** [comment]
Thanks. This is great. Monet js uses cata in a way it only supports evaluation with either. It.got me stuck trying to match on functors in custom interpreter. 

I am mostly interested in using it for fetching strategies. Something like FB HAXL or clojure muse project, but simpler one i guess.

@joneshf whould be great if you continue with library, adding comments and docs. Etc. I am still wrapping my head around some details. I love though how you used cata to delegate matching to actual objects. Are you interested on building real fetching dsl with interpreter (and optymiser?) Let me know if i can contribute somehow. :-) would love to see that kind of magic working in JS

**Comment by joneshf** [comment]
@SimonRichardson I don't think I ever finished that, actually. You're better off looking at the scala version if you want to understand it. There's a good chance that I didn't do `Free` right, and that's what stopped me from continuing.

@ev45ive I'll keep you posted.

**Comment by SimonRichardson** [comment]
@joneshf Yeah, i'm in the process of fixing it :) 

Two of the three interpreters work now, just working out how to fix the tweet one. I think essentially you'd mixed up the scala Free monads, so one from scalaz-seven and 7.x.x.

You've finally made me learn it, so that's really good!! Do you want me to open a PR to fix your repo, or you happy to leave it as an experiment?

Here is [my version](https://github.com/SimonRichardson/fantasia), heavily inspired by yours (:+1:), but i'm using fantasyland components rather making everything from scratch. Also @ev45ive you get catamorphisms for free with [daggy](https://github.com/puffnfresh/daggy), which saves loads of boiler plate.

https://github.com/SimonRichardson/fantasia
