### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nschurmann** [fantasyland/fantasy-land#116]
Where can i find more documentation on what the methods should do?, the documentations specify the data that should return, but not how it should behave. IE:

`equals` doesn't tell that a.equals(b) should return true only if `a === b`, or `a == b`, or `a: 'string' & b: 'string '`

**Comment by nschurmann** [comment]
For my understanding of the documentation, in the example of `equals`

you can return true the whole time and still match this specification. (i know the meaning of equals, but it was the best example, as i don't know how the other methods should behave).

**Comment by 5outh** [comment]
The idea is that the specification should actually lead you to the implementation; if you can come up with a `Setoid` with an `equals` method that follows the laws mentioned in the specification, you've got something that, in some way, behaves like an equivalence.

The naming comes directly from the mathematical structure of the same name: https://en.wikipedia.org/wiki/Setoid

which is defined as a set or a type along with an equivalence relation: https://en.wikipedia.org/wiki/Equivalence_relation

An equivalence relation doesn't really have any concept of "what it means to be equivalent" other than the laws must hold; that is what this specification is trying to encode in Javascript.

You're right that returning `true` (or `false`) for every comparison is a valid `equals` method, and that's totally fine! If you want your objects to trivially be equal no matter what, you have a setoid. The laws are actually all that matter (and that's the point)!

**Comment by nschurmann** [comment]
Thanks for the clarification @5outh 

I'm having troubles on learning the behaviour of some of this methods (like apply ap, lift, among others), is there some documentation elsewhere in javascript that i can read to understand this behaviours?

**Comment by 5outh** [comment]
@nschurmann Understanding the reasoning behind this stuff is a bit tricky in Javascript because it's not a widely used pattern in the language, unfortunately. There are several libraries that implement some of the fantasy-land structures listed in [Implementations](https://github.com/fantasyland/fantasy-land/blob/master/implementations.md) if you'd like to dig around.

The idea behind `ap` is that if you have a thing that, in some sense, "contains" a function from `a -> b`, and another thing of the same type that contains `a`s, `ap` turns the second thing into a thing that contains `b`s. Many things allow this pattern; there is an example implementation for the "singleton container" type (called `Id`) in [id.js](https://github.com/fantasyland/fantasy-land/blob/master/id.js). The next step would probably be to look at an implementation of the `Maybe` applicative somewhere.

I'm not actually seeing `lift` in the spec, but the term usually means something along the lines of "take my thing and wrap it in a new thing to give it more functionality;" I don't know if that's particularly helpful though.

**Comment by CrossEye** [comment]
@nschurmann: You also [asked for][rf] documentation of the Ramda-Fantasy types.  Although that doesn't seem to be happening quickly, it's a more logical place to get the sort of details you're looking for.  That project presents specific types, `Maybe`, `Either`, `Future`, etc.  Learning a bit about what these types do will probably also help learn what the abstract types like `Functor` or `Apply` actually mean.

Probably the most stable version of some of these types is in [Folktale][ft].  They also have reasonably good documentation, so that might be a place to start.

  [ft]: https://github.com/folktale
  [rf]: https://github.com/ramda/ramda-fantasy/issues/60#issuecomment-155591015

**Comment by ctrlplusb** [comment]
@nschurmann [Monet.js](https://cwmyers.github.io/monet.js) is also pretty nice.

**Comment by SimonRichardson** [comment]
Implementations of each method is up to the library creator(s), as long as they satisfy the specification I'm happy to leave this open ended. Reopen if you don't agree :dancer:
