### ISSUE TITLE
Traversable says it only needs Foldable+Functor, but later on it requires Applicative

### ISSUE THREAD

**Issue by Qqwy** [fantasyland/fantasy-land#143]
I am not fully understanding how Traversable should work, but it first states

> A value that implements the Traversable specification must also implement the Functor and Foldable specifications.

But then it says:

> of must return the Applicative that u contains.

Is this correct and am I misunderstanding what is described here, or is this incorrect?

**Comment by joneshf** [comment]
There's no contradiction. But it's tough to understand without types.

The data type you're defining `Traversable` instance for does need to be a `Functor` and it also needs to be a `Foldable`. The data type you're defining `Traversable` instance for does **NOT** need to be an `Applicative`.

The function that you define to implement `Traversable` is `sequence`. In order to call `sequence`, the value of your data type **MUST** have be an `Applicative`. And, `of` must return the same `Applicative` as the value of your data type.

Again, this is much easier with types, but maybe some examples would help.

* https://github.com/fantasyland/fantasy-land/blob/6692bb31e56c15766dcf274a2e0cfe3ed8bc80cc/id.js#L42-L46
* https://github.com/fantasyland/fantasy-options/blob/56cd68872e681e7abe45d1d0304af53d7a819dcf/src/option.js#L70-L78
* https://github.com/fantasyland/fantasy-eithers/blob/265680c3bcbf0246a2a14bca6ef683b4b55efc13/src/either.js#L52-L60

**Comment by Qqwy** [comment]
I see! Thank you for this clarification. So `Traversable.sequence`'s behaviour is only specified when the _contained_ data type is `Applicative`, i.e. has a valid definition of `Applicative.of`.

**Comment by joneshf** [comment]
Exactly!
