### ISSUE TITLE
[Question] Type signature for ap

### ISSUE THREAD

**Issue by shineli1984** [fantasyland/fantasy-land#298]
I had a look at a few fantasy-* repos where `ap` method is derived as below
```js
SomeApplicative.prototype.ap = function(a) { return this.chain(f => a.map(f)) }
``` 
In the current ap type signature `ap :: Apply f => f a ~> f (a -> b) -> f b`, my understanding is that `f a` refers to `this` in the above method.

So I'm wondering if the type signature for `ap` should be:
```js
ap :: Apply f => f (a -> b) ~> f a -> f b
```
?

**Comment by Avaq** [comment]
See also:

* https://github.com/fantasyland/fantasy-land/issues/169
* https://github.com/fantasyland/fantasy-land/issues/181
* https://github.com/fantasyland/fantasy-land/issues/228
* https://github.com/fantasyland/fantasy-land/issues/242
* https://github.com/fantasyland/fantasy-land/issues/283

How `ptotoype.ap` is implemented is up to library authors. Most of the time, it will be as `ap :: Apply f => f (a -> b) ~> f a -> f b`, because it favours readability when fluent-method chaining.

Fantasy land doesn't specify `ap`. It specified `fantasy-land/ap`, and that one is the other way around.

**Comment by shineli1984** [comment]
Thanks for the explaination.
