### ISSUE TITLE
Remove all OOP features

### ISSUE THREAD

**Issue by Ne4to777** [fantasyland/fantasy-land#329]
Hi! I really don't understand why programmers need OOP features in FP (like **this**, **new** and оthers). Looks like you don't believe in the FP paradigm and this specification is written for educational purposes only

**Comment by MarisaKirisame** [comment]
> 
> 
> > > Аnd this is why "reduce" will always be a problem
> > 
> > 
> > Why is that? It's not obvious to me.
> 
> the code inside was difficult to write through composition, so you wrote it imperatively. Therefore, the FP dies.

I am very confused about the flow of the conversation.
For starter, ultimately, if you find some code unsatisfactory, you... fix the code and open a pull request?

Another thing is, I dont think "the code is in x style" is a good argument. people write code as an mean, not as an end.

"The code has error/is complex/inefficient/make reasoning hard because it screw up invariance“ is some of them, but "the code is written in imperative style" isnt really one IMO. (yes, mutable reference screw invariance and reasoning hard, but the code you object to is only using local variable). You can rewrite it with state monad or with recursion in general... but the code is "the same" - you only push the reasoning complexity inside the monad/the call stack.

And at the end of the line, "all code should be written using FP" is just a weird assumption. There are a plethora of domain out there, that can be written by one single person, but the SOTA isnt written in FP. Some example is chess engine, egraph, linear algebra, HPC. If fp die here, fp is dead everywhere.

**Comment by puffnfresh** [comment]
Functional programming can use `this` and `new`. They don't break functions.

They may or may not be "OOP features" - whatever that means. Nobody cares.

**Comment by Ne4to777** [comment]
> Functional programming can use `this` and `new`. They don't break functions.

No, it can`t. Otherwise call it FOOP.

**Comment by CrossEye** [comment]
@Ne4to777:

Care to give the definitive definition of FP and OOP and then use them to explain why FP code cannot interact with OOP code?

>>> Аnd this is why "reduce" will always be a problem

>> Why is that? It's not obvious to me.

> the code inside was difficult to write through composition, so you wrote it imperatively. Therefore, the FP dies.

JS's poor recursion support means that many things cannot be written internally as cleanly as they might be in, say, Haskell.  That doesn't mean they don't support an API that is FP.

**Comment by Ne4to777** [comment]
@CrossEye , what do you mean by poor support?

**Comment by CrossEye** [comment]
@Ne4to777: Are  you simply trolling here?

It's well-known that JS has low recursion stack limits.  Last I knew (maybe 2019) most browsers were in the 10,000 - 20,000 call range, except that Safari went to 30,000.  Moreover, although tail-call optimization [has been specified][sp] since ES2015, almost all engines [are ignoring this][kt].  So one cannot run recursive code against large data.  And even against smaller data, the overhead is often performance-prohibitive.  (For a case study, see [Eweda][ew], the predecessor to [Ramda][ra], which had elegant recursive code but couldn't perform.)

Recursion is a much cleaner way to write FP code; it can be done without variable reassignment, and often much more simply than its imperative alternatives.  But since we cannot use it in JS unless we know the data is fairly small, we can't use it to build libraries.

  [ew]: https://github.com/CrossEye/eweda
  [kt]: https://kangax.github.io/compat-table/es6/#test-proper_tail_calls_(tail_call_optimisation)
  [ra]:https://github.com/ramda/ramda
  [sp]: https://262.ecma-international.org/6.0/#sec-tail-position-calls

**Comment by Ne4to777** [comment]
@CrossEye , You said about browsers, but what does this have to do with javascript? Or then show me infinite recursion in Haskell in any browser.

We are discussing the concept, not the implementation. The scarcity of resources today should not kill the theory of tomorrow.

**Comment by bergus** [comment]
@Ne4to777 You seem to be missing the fact that the fantasy-land interoperability specification is, despite the name, no pipe dream of tomorrow but rather a practical tool for today.

**Comment by Ne4to777** [comment]
@bergus , that is, is it okay to use context in a contextless paradigm?

**Comment by CrossEye** [comment]
@Ne4to777:

> We are discussing the concept, not the implementation. The scarcity of resources today should not kill the theory of tomorrow.

I have no idea what you're discussing.  Most of us here are discussing a specification for data types with useful commonalities.

Moreover, a specification that cannot be implemented due to practical concerns is simply a work of fantasy.

**Comment by bergus** [comment]
*PLONK*
