### ISSUE TITLE
Traversable and Foldable use multiple variables as arguments

### ISSUE THREAD

**Issue by Ne4to777** [fantasyland/fantasy-land#330]
It is bad for composition. Maybe it should be curried? Тhe comma looks like a new syntax element in the context of FP.

**Comment by CrossEye** [comment]
@Ne4to777: 

One of the major design constraints for this specification was that it is meant to work as closely as possible to existing Javascript tools.  There are reasons the functions are called, for instance, `map` and `reduce` rather than `fmap` and `foldl`.  This makes integration with standard JS built-in types as seamless as possible.  But `Foldable`'s `reduce` won't work with arrays if we change the signature of the callback.

When FantasyLand moved to namespaced functions, the specification *could* have made a different call, since there was no direct link between `a ['reduce']` and `a ['fantasy-land/reduce']`.  But that would have precluded the easy aliasing path to upgrade that many libraries used then and probably still use.

As David Chambers pointed out above, this specification is all about interoperability.  It is not a prescriptive treatise on how to write FP code.

**Comment by Ne4to777** [comment]
@CrossEye , 
Which JS tools are trying to approach traversable?
How naming interferes with FP?
If we have already created own namespace for reduce, why don't we make it curried?

**Comment by davidchambers** [comment]
> If we have already created own namespace for reduce, why don't we make it curried?

There is no need to do so. The function you desire can already be defined:

```javascript
> S.reduce
reduce :: Foldable f => (b -> a -> b) -> b -> f a -> b

> S.reduce (xs => x => [x, ...xs]) ([]) ([1, 2, 3, 4, 5])
[5, 4, 3, 2, 1]

> S.reduce (s => t => s + t) ('foo') (S.Just ('bar'))
'foobar'
```

**Comment by Ne4to777** [comment]
@davidchambers , yes, that's exactly what i'm talking about
