### ISSUE TITLE
Just an idea: Why not make `LiftN` the requirement for applicatives rather than `ap`?

### ISSUE THREAD

**Issue by russellmcc** [fantasyland/fantasy-land#56]
It seems like in a language like JavaScript where currying isn't the norm (and might not be performant because of a lack of compiler help), it might be more useful to make something more like `LiftN` the requirement for applicative rather than `ap`.  It could even be backwards compatible for non-library code by just allowing `ap` to take multiple arguments like this:

```
MyApp.of(f).ap(a, b, c, d, e)
```

This would be fairly easy to implement for most applicatives I can think of, and would certainly be more convenient for the user and probably more performant, too.

If this doesn't match the aesthetics of fantasy-land (and my guess is it doesn't), maybe there should be a way for implementors to optionally provide a `liftN` method (under some friendlier name, maybe just `lift`) for performance reasons?

**Comment by bergus** [comment]
I think we should revisit this (I want to implement it :-)).
Making a [`liftA2`](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Applicative.html#v:liftA2) (or [`liftF2`](http://hackage.haskell.org/package/semigroupoids-5.0.0.2/docs/Data-Functor-Apply.html#v:liftF2)) function the alternative definition of `Apply` seems very attractive (would be placed at `seq` in @phadej's diagrams). I guess that it's more often needed than `ap`. Of course they can be derived from each other, but making `lift` is a bit ugly in JS as it requires currying.
```js
function ap(af, ax) {
    function call(f, x) { return f(x); }
    return lift(call, af, ax);
}
function lift(f, ax, ay) {
    var f_curried = function(x) { return function(y) { return f(x, y); }; };
    return ax.map(f_curried).ap(ay);
}
```
I don't think we should make this a method though but rather a static function, and I cannot really envision a name for it either: `ax.apWith(f, ay)` sounds wrong because we're not applying `ax` but rather `f`, and I really don't want to build upon [`thrush`](http://hackage.haskell.org/package/data-aviary-0.4.0/docs/Data-Aviary-BirdsInter.html#v:thrush) or *T-combinator* (see [this SE question](http://programmers.stackexchange.com/q/198575/66652) for references).

----
Of course, a variadic `liftN` function might be even more useful (easier to implement and call). It's quite common in libraries, e.g. as [`combineWith` in Bacon](https://github.com/baconjs/bacon.js#bacon-combinewith), or [`join` in Bluebird](http://bluebirdjs.com/docs/api/promise.join.html). There are versions that optionally take arrays as inputs instead, and I think that's a route we could go down as well to make a proper binary function (array + fn), as we've seen that generic libraries like Ramda which use currying don't really like variadic functions. Yet after all this might fit better with Applicative than in Apply (which cannot handle the nullary case), and in this case I think we might just introduce an optional `sequence` function that could be used like
```js
sequence([ax, ay, az, …]).map(function([x, y, z, …]) {
    …
});
```
which already looks a lot like that `tfil` idiom that was suggested. Implementing `sequence` in a library is probably much more efficient than deriving it as
```js
function sequence(arr) {
    return arr.reduce(function(ar, ax) {
        return ar.map(function(res) {
            return function(x) {
                res.push(x);
                return res;
            };
        }).ap(ax);
   }, of([]));
}
```

**Comment by SimonRichardson** [comment]
Is this going to happen, or should I close it for now?
