### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#96]
If a new major version of the spec is to be published, let's consider which changes should be made at that time. It's a rare opportunity to consider changes which are both breaking and nonessential.

I'd like to see:
- prefixed method names (#92);
- `Monoid#empty` changed from nullary function to identity element (#82); and
- precedence of `.{empty,of}` and `.constructor.{empty,of}` specified, or the prototype properties removed from the spec (#88).

Which other issues should be considered?

**Comment by bergus** [comment]
If we solve #88, we might also want to specify how the functions need/can be called:
* they need to be called as methods (with `this`) - seems to already be implied
* they can be called on arbitrary instances, not only the one they're accessed on

The latter point would allow a "type" to be exported as an object like `{equals, empty, concat}` so they can be accessed on that type and be applied on any data using `.call`.

**Comment by bergus** [comment]
Has anyone considered reifying type classes in JavaScript? Have a good read of this article: http://www.haskellforall.com/2012/05/scrap-your-type-classes.html (and to a lesser extent, maybe also https://www.fpcomplete.com/user/jfischoff/instances-and-dictionaries and https://www.joachim-breitner.de/blog/398-Making_dictionary_passing_explicit_in_Haskell).
I think this should solve (most of) our problems with type inference - by just always explicitly passing the class instance; instead of trying to infer it from the value (which does not always work well, especially if the function is nullary or the value has multiple instances).
Fantasyland would then only spec the interface for the type dictionaries, not the interface (methods) of the values themselves. Although we might still want to additionally standardise a way to get the "default type" of a value.

**Comment by puffnfresh** [comment]
@bergus I would like to see the spec rewritten to look like that. I think it'd be useful!

**Comment by bergus** [comment]
I've got it in the works, but it's going to look *very* different than the current one.

**Comment by puffnfresh** [comment]
@bergus awesome, I'd like to see it! It's going to come down to trade-offs on where we go, but I think we can recognise the current form is inadequate for a lot of uses.

**Comment by CrossEye** [comment]
I'm looking forward to seeing it.  I've thought a lot on the same issue, but don't feel educated enough in this area yet to make my own proposal.  I'm in the middle of a number of projects, and have for the moment put aside one that seems related; perhaps now I'll get back to this.

**Comment by SimonRichardson** [comment]
@bergus I'm interested in this also, let me know when there is something up to glance at. Even if it's incomplete.

**Comment by rpominov** [comment]
I took a stub in rewriting spec with methodless approach. Each type represented as a dictionary with functions, that operate on type's values. Put it together only to see how it feels: https://gist.github.com/rpominov/b8537ec4cdebd3cc96ef

I have no idea how practical could it be to use that spec, we probably would need to pass type objects around a lot. But it certainly have benefits, for instance we can define multiple types that operate on same values (e.g. two Monoids for booleans, based on `||` and `&&`).

**Comment by rpominov** [comment]
I'm working on a [spec that uses static functions instead of methods](https://github.com/rpominov/static-land/blob/master/docs/spec.md)

Still exploring whether this approach can be usable, but seems promising. Some interesting results so far:

 - We can [automatically derive](https://github.com/rpominov/static-land/blob/883c94c09990454b43a4721e5c914db9d9e4f4b7/src/derive.js#L44) missing methods for a static-land type 
 - We can [convert fantasy-land type to a static-land one](https://github.com/rpominov/static-land/blob/883c94c09990454b43a4721e5c914db9d9e4f4b7/src/fromProto.js) (Probably same can be done other way around)
 - I also working on an [reactive streams](https://github.com/rpominov/basic-streams) library which main API is close to a static-land type, I'm going to make it fully compatible with static-land and then make it possible to do `StreamOfEither = Stream.compose(Either)` where `Stream`, `Either`, and `StreamOfEither` are static-land types. I have a POC of such composition with fantasy-land types https://github.com/rpominov/basic-streams/issues/11

**Comment by SimonRichardson** [comment]
Yeah, it would be good to see how something like `Either`, `Free` or `Lenses` can be modeled with this and it might solve some ambiguity in the spec.

**Comment by rpominov** [comment]
`Either` can be implemented in static-land using something like `{tag: 'left', value: 1}` as instances (just data), or an static-land type can be automatically created for any existing FL compatible `Either`, using converter I mentioned above.

As for `Free` and `Lenses` I didn't even thought about it yet, and I don't understand these concepts very well to be honest. Yet to learn.

**Comment by ccorcos** [comment]
How do you implement a polymorphic `map` then? It would be pretty frustrating to have to carry around a dozen different function for map, reduce, etc.

**Comment by rpominov** [comment]
Yeah, this is the trade of: we get [some advantages](https://github.com/rpominov/static-land/blob/master/docs/spec.md#pros) in exchange of having to pass type objects around for any polymorphic code. So I'm trying to explore how frustrating this is, maybe it's not so bad.

**Comment by ccorcos** [comment]
I understand. Well keep me posted on how it goes!

**Comment by CrossEye** [comment]
My version has been stalled for months, and will be stalled for at least a few weeks more, but my idea was  to have a run-time type registry:  If you let the system know that the `map` for your Functor is a given function, when the generic `map` is called with your type, it can simply look it up and call that version.

**Comment by SimonRichardson** [comment]
https://github.com/puffnfresh/bilby.js worked like this, in fact I move the
environment stuff to fantasyland for use in testing.

**Comment by rpominov** [comment]
I've created an issue about registry https://github.com/rpominov/static-land/issues/3 . By the way, we should probably discuss matters related strictly to static-land in issues of static-land repo, if anyone interested. I don't want to spam here too much :)

**Comment by joneshf** [comment]
Can this be closed? 2.1.0 is out, so I assume we addressed the concerns this issue had.
